[package]
name = "zeekit"
version = "0.6.1"
edition = "2021"
authors = ["Keyvan Kambakhsh <keyvankambakhsh@gmail.com>"]
description = "Cryptography primitives and SNARK gadgets for Zeeka Network"
repository = "https://github.com/zeeka-network/zeekit"
homepage = "https://github.com/zeeka-network/zeekit"
license = "MIT"

[dependencies]
hex = "0.4"
rand = "0.8.5"
lazy_static = "1.4.0"
num-bigint = "0.4"
num-integer = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
ff = { version = "0.12", features = ["derive", "derive_bits"] }

dusk-plonk = { version = "0.10.0", optional = true }
dusk-jubjub = { version = "0.11.1", optional = true }
dusk-bytes = { version = "0.1.5", optional = true }

bellman = { version = "0.13.0", optional = true }
bls12_381 = { version = "0.7.0", optional = true }


[features]
default = []
plonk = ["dusk-plonk", "dusk-jubjub", "dusk-bytes"]
groth16 = ["bellman", "bls12_381"]
