[package]
name = "zeekit"
version = "0.1.0"
edition = "2021"
authors = ["Keyvan Kambakhsh <keyvankambakhsh@gmail.com>"]
description = "Cryptography primitives and SNARK gadgets for Zeeka Network"
repository = "https://github.com/zeeka-network/zeekit"
homepage = "https://github.com/zeeka-network/zeekit"
license = "MIT"

[dependencies]
dusk-plonk = "0.10.0"
dusk-jubjub = "0.11.1"
dusk-bytes = "0.1.5"
rand_core = "0.6.3"
lazy_static = "1.4.0"
num-bigint = "0.4"
num-integer = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
ff = { version = "0.11", features = ["derive"] }
